sampleTable: "samplesheet.tsv"
genome: ""
blastdbase: ""
star_index_dir: ""
strandedness: "" # options are "rf" for dUTP, "fr' for ligation-stranded e.g. Illumina TruSeq, or "" for unknown or unstranded
aligner: "STAR"

td2: True
